version: "3.8"

services:
  postgres:
    image: "postgres:12"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: watershed
